drone:
  build: .
  command: nodemon app/index.js
  links:
   - db1
   # - db2
   # - db3
  # ports:
  #  - "3100:3000"
  volumes:
   - ./app:/home/drone-overmind/app
  environment: 
   NODE_ENV: development
db1:
  image: rethinkdb:latest
  command: rethinkdb --canonical-address 192.168.59.103 --bind all --cache-size 1024
  ports:
   - "28015:28015"
   - "29015:29015" 
   - "8080:8080"
# db2:
#   image: rethinkdb:latest
#   command: rethinkdb --join 192.168.59.103:29015 --bind all --cache-size 1024
#   ports:
#    - "28016:28015"
#    - "29016:29015" 
#    - "8081:8080"
# db3:
#   image: rethinkdb:latest
#   command: rethinkdb --join 192.168.59.103:29015 --bind all
#   ports:
#    - "28017:28015"
#    - "29017:29015" 
#    - "8082:8080"