overmind:
  build: .
  command: nodemon app/index.js
  links:
   - overmindDB
  ports:
   - "8080:8080"
  volumes:
   - ./app:/home/drone-overmind/app
  environment: 
   NODE_ENV: development
   DB_HOST: overmindDB
   SOCKET_IO_PORT: 8080
overmindDB:
  image: rethinkdb:latest
  # command: rethinkdb --bind all --cache-size 1024
  # command: rethinkdb --bind all --canonical-address 192.168.59.103 --cache-size 1024
  ports:
   - "28015:28015"
   - "29015:29015" 
   - "8081:8080"
  # mem_limit: 2G
# db2:
#   image: rethinkdb:latest
#   command: rethinkdb --join 192.168.59.103:29015 --bind all --cache-size 1024
#   ports:
#    - "28016:28015"
#    - "29016:29015" 
#    - "8081:8080"
# db3:
#   image: rethinkdb:latest
#   command: rethinkdb --join 192.168.59.103:29015 --bind all
#   ports:
#    - "28017:28015"
#    - "29017:29015" 
#    - "8082:8080"